services:
  node-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    command: sh -c "npm install && npx nodemon --exec ts-node src/server.ts"
    ports:
      - "23000:3000"
    environment:
      SUPABASE_ACCESS_TOKEN: ${SUPABASE_ACCESS_TOKEN}